schemaVersion: "0.0.1"
kind: "studio-config"
session:
    description: "Seqera Studio R-IDE"
    template:
        kind: "registry"
        registry: "public.cr.seqera.io/platform/data-studio-ride:2026.01.2-0.12.2"
        # kind: "dockerfile"        <-- uncomment if you want to customize the image
        # dockerfile: "Dockerfile"  <-- path to your custom Dockerfile
